CREATE TABLE IF NOT EXISTS PLAYER (
    id SERIAL PRIMARY KEY, 
    name CHARACTER(30) UNIQUE NOT NULL, 
    ranking REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS GAME (
    id SERIAL PRIMARY KEY,
    insertion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    score REAL DEFAULT NULL
);

-- TODO: add ranking after game field
CREATE TABLE IF NOT EXISTS PLAYER_GAME (
    id SERIAL PRIMARY KEY, 
    player_id INTEGER NOT NULL REFERENCES PLAYER,
    game_id INTEGER NOT NULL REFERENCES GAME,
    kills INTEGER NOT NULL,
    suicides INTEGER NOT NULL,
    position INTEGER NOT NULL,
    score REAL NOT NULL,
    ranking_delta REAL NOT NULL,
    UNIQUE (player_id, game_id)
);

CREATE TABLE IF NOT EXISTS GAME_AVG_SCORE(
    id SERIAL PRIMARY KEY,
    game_id INTEGER UNIQUE NOT NULL REFERENCES GAME,
    insertion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    avg_score REAL DEFAULT 0
);